export enum TipoPropiedad {
  CASA = "CASA",
  DEPARTAMENTO = "DEPARTAMENTO",
  TERRENO = "TERRENO",
  LOCAL = "LOCAL",
}

export enum Operacion {
  VENTA = "VENTA",
  ALQUILER = "ALQUILER",
}

export enum EstadoPropiedad {
  BORRADOR = "BORRADOR",
  PUBLICADA = "PUBLICADA",
  RESERVADA = "RESERVADA",
  PAUSADA = "PAUSADA",
  VENDIDA = "VENDIDA",
  ALQUILADA = "ALQUILADA",
  CANCELADA = "CANCELADA",
}

export enum EstadoSolicitudVisita {
  PENDIENTE = "PENDIENTE",
  CONFIRMADA = "CONFIRMADA",
  REALIZADA = "REALIZADA",
  CANCELADA = "CANCELADA",
  RECHAZADA = "RECHAZADA",
}

export enum TipoActividad {
  COMENTARIO = "COMENTARIO",
  SOLICITUD_VISITA = "SOLICITUD_VISITA",
  CAMBIO_ESTADO_PROPIEDAD = "CAMBIO_ESTADO_PROPIEDAD",
  RESENA = "RESENA",
}
